# Generated by Django 5.2.4 on 2025-07-22 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('immigration', '0001_initial'),
    ]

    operations = [
    ]
