# Generated by Django 5.2.4 on 2025-07-22 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immigration', '0002_fix_migration_dependencies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traveldocument',
            options={'ordering': ['-created_at'], 'verbose_name': 'Travel Document', 'verbose_name_plural': 'Travel Documents'},
        ),
        migrations.AlterModelOptions(
            name='traveldocumentchild',
            options={'verbose_name': 'Travel Document Child', 'verbose_name_plural': 'Travel Document Children'},
        ),
        migrations.AddField(
            model_name='traveldocument',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='traveldocument',
            name='document_number',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Lambaraka Warqadda'),
        ),
        migrations.AddField(
            model_name='traveldocument',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='travel_documents/photos/', verbose_name='Sawirka'),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Taariikhda Dhalasho'),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100, verbose_name='Goobta Dhalasho'),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='card_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Card Number'),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='citizen_card',
            field=models.CharField(blank=True, max_length=50, verbose_name='Card-ka Muwadinka'),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Taariikhda'),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='Degmada'),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Magaca oo Afaran'),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='identification_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Aqoonsi Lambar'),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='immigration_officer_notes',
            field=models.TextField(blank=True, verbose_name='Faahfaahin Gaar ah'),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='job_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nooca Shaqo'),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Liisan Lambar'),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='mother_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Magaca Hooyada'),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, verbose_name='Jinsiyadda'),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='officer_signature',
            field=models.CharField(blank=True, max_length=200, verbose_name='Signature'),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telephone Lambar'),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='Gobolka'),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='region_office',
            field=models.CharField(blank=True, max_length=100, verbose_name='Xafiiska Gobolka'),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='sponsor_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Magaca Wakiilka'),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='status',
            field=models.CharField(blank=True, choices=[('filled', 'Waa la Buxiyay'), ('approved', 'Waa la Ogolaaday'), ('printed', 'Waa la Daabacay')], max_length=10, verbose_name='Xaaladda'),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='workplace',
            field=models.CharField(blank=True, max_length=100, verbose_name='Goobta Shaqo'),
        ),
        migrations.AlterField(
            model_name='traveldocumentchild',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Taariikhda Dhalasho'),
        ),
        migrations.AlterField(
            model_name='traveldocumentchild',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100, verbose_name='Goobta Dhalasho'),
        ),
        migrations.AlterField(
            model_name='traveldocumentchild',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Magaca'),
        ),
        migrations.AlterField(
            model_name='traveldocumentchild',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='travel_documents/children/', verbose_name='Sawirka'),
        ),
    ]
