# Generated by Django 5.2.4 on 2025-07-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immigration', '0003_alter_traveldocument_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traveldocument',
            options={},
        ),
        migrations.AlterModelOptions(
            name='traveldocumentchild',
            options={},
        ),
        migrations.RemoveField(
            model_name='traveldocument',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='traveldocument',
            name='document_number',
        ),
        migrations.RemoveField(
            model_name='traveldocument',
            name='photo',
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='card_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='citizen_card',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='identification_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='immigration_officer_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='job_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='license_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='mother_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='officer_signature',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='region_office',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='sponsor_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='status',
            field=models.CharField(blank=True, choices=[('filled', 'Waa la Buxiyay'), ('approved', 'Waa la Ogolaaday'), ('printed', 'Waa la Daabacay')], max_length=10),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='workplace',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='traveldocumentchild',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='traveldocumentchild',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='traveldocumentchild',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='traveldocumentchild',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='travel_photos/'),
        ),
    ]
