# Generated by Django 5.2.4 on 2025-07-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immigration', '0005_alter_traveldocument_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveldocument',
            name='filled_date',
            field=models.DateField(blank=True, null=True, verbose_name='Taariikhda la buuxiyay'),
        ),
        migrations.AddField(
            model_name='traveldocument',
            name='has_company_license',
            field=models.BooleanField(default=False, verbose_name='Liisanka Shirkada'),
        ),
        migrations.AddField(
            model_name='traveldocument',
            name='has_damaged_id',
            field=models.BooleanField(default=False, verbose_name='Aqoonsiga Ladamiintaha'),
        ),
        migrations.AddField(
            model_name='traveldocument',
            name='has_notayo',
            field=models.BooleanField(default=False, verbose_name='Notaayo'),
        ),
        migrations.AddField(
            model_name='traveldocument',
            name='has_other_documents',
            field=models.BooleanField(default=False, verbose_name='Hadii wax kale jiro'),
        ),
        migrations.AddField(
            model_name='traveldocument',
            name='has_sponsor_id',
            field=models.BooleanField(default=False, verbose_name='ID-ga Kafiilka'),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='status',
            field=models.CharField(blank=True, choices=[('filled', 'Waa la Buxiyay'), ('approved', 'Waa la Ogolaaday'), ('printed', 'Waa la Daabacay')], max_length=10, verbose_name='Marxalada uu marayo'),
        ),
    ]
