# Generated by Django 5.2.4 on 2025-07-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immigration', '0006_traveldocument_filled_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveldocument',
            name='status',
            field=models.CharField(blank=True, choices=[('filled', 'Waa la Buxiyay'), ('approved', 'Waa la Ogolaaday'), ('printed', 'Waa la Daabacay')], max_length=10, verbose_name='Marxalada uu Marayo'),
        ),
    ]
